resume_videos=['<iframe width="560" height="315" src="https://www.youtube.com/embed/Tt08KmFfIYQ?si=L0dwZRa-iTK1Fv5q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/XJ7bYdjKDcA?si=uJeM8wihMwIHSEp6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/Ll62YIkEvs8?si=eljCE5iBs3u2_sOr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/u75hUSShvnc?si=tXstTTg5HrwHWVKI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        '<iframe width="560" height="315" src="https://www.youtube.com/embed/Bip6BXtOQ_I?si=_t_wtKt4U48OLrDU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>']

interview_videos=['<iframe width="560" height="315" src="https://www.youtube.com/embed/0siE31sqz0Q?si=wgu7cB5UQsYwXDBo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                  '<iframe width="560" height="315" src="https://www.youtube.com/embed/0JhwGUeG3Oc?si=yi3j_ljZP__kp1t_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                  '<iframe width="560" height="315" src="https://www.youtube.com/embed/ggVLt8FEGHc?si=Gdtj4-jjHGh4m5tH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                  '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZU9x1vFx5lI?si=QdFP1CTA-_VMdV4x" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
                  '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZMByWenSRdI?si=oFUBANbjTpPrxlhi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>']